# skills_db.py

# List of common and job-relevant skills (ATS-friendly)
SKILLS_DATABASE = [
    "sql",
    "excel",
    "python",
    "html",
    "css",
    "javascript",
    "git",
    "power bi",
    "tableau",
    "data analysis",
    "data visualization",
    "machine learning",
    "deep learning",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "communication",
    "problem solving",
    "teamwork",
    "leadership",
    "project management",
    "data cleaning",
    "data mining",
    "agile",
    "scrum",
    "django",
    "flask",
    "sql server",
    "mysql",
    "mongodb",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "tensorflow",
    "keras",
    "scikit-learn",
    "opencv",
    "nlp",
    "powerpoint",
    "presentation",
    "reporting"
]